### ISSUE TITLE
Tracking issue for axum 0.7 migration

### ISSUE THREAD

**Issue by blaenk** [Altair-Bueno/axum-template#38]
- Changelog (migration notes) https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md
- Blog post https://tokio.rs/blog/2023-11-27-announcing-axum-0-7-0

**Comment by Altair-Bueno** [comment]
Thanks for the heads up!

If i'm not mistaken, the changes required are ready on https://github.com/Altair-Bueno/axum-template/pull/39. Test passes, yet i'm not sure if everything is working as expected. I still need to read the breaking changes and see if there is anything working differently. But the library compiles and you can run it locally by setting this in Cargo.toml

```toml
[dependencies.axum-template]
git = "https://github.com/Altair-Bueno/axum-template.git"
branch = "dependabot/cargo/axum-0.7.1"
```
